'use client';

import { useEffect, useRef } from 'react';
import type { PollingUnitDetail, VerificationStatus } from '@/lib/types';
import {
  buildLayers,
  buildSources,
  NIGERIA_BOUNDS,
  NIGERIA_CENTER,
} from '@/lib/mapbox-style';

interface Props {
  electionId: string;
  token: string;
  onSelect: (unit: PollingUnitDetail) => void;
}

const STATUS_INT_TO_NAME: Record<number, VerificationStatus> = {
  0: 'no_data',
  1: 'single_source',
  2: 'inec_published',
  3: 'consensus',
  4: 'discrepancy',
  5: 'inec_confirmed',
  6: 'inec_conflict',
};

// Real Mapbox GL JS renderer. The map mounts only when a token is
// available; otherwise the parent component uses the SVG fallback. The
// vector tiles come from /api/v1/tiles, generated by PostGIS ST_AsMVT.
//
// We dynamic-import mapbox-gl because the package touches `window` and
// `document` at module load - it must not run during SSR.

export function MapboxRenderer({ electionId, token, onSelect }: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<any>(null);

  useEffect(() => {
    if (!containerRef.current) return;
    let cancelled = false;

    (async () => {
      const mod = await import('mapbox-gl');
      // Mapbox GL CSS is imported at page level (see map/page.tsx).
      if (cancelled || !containerRef.current) return;

      const mapboxgl = (mod as any).default ?? mod;
      mapboxgl.accessToken = token;

      const tileBase =
        typeof window !== 'undefined'
          ? `${window.location.origin}/api/v1/tiles`
          : '/api/v1/tiles';

      const map = new mapboxgl.Map({
        container: containerRef.current,
        style: {
          version: 8,
          name: 'OpenBallot',
          glyphs: 'https://api.maptiler.com/fonts/{fontstack}/{range}.pbf',
          sources: {
            ...buildSources(electionId, tileBase),
            'osm-raster': {
              type: 'raster',
              tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
              tileSize: 256,
              attribution: '© OpenStreetMap contributors',
            },
          },
          layers: [
            { id: 'osm', type: 'raster', source: 'osm-raster' },
            ...(buildLayers() as any[]),
          ],
        },
        center: NIGERIA_CENTER,
        zoom: 5.5,
        minZoom: 4,
        maxZoom: 17,
        maxBounds: [
          [NIGERIA_BOUNDS[0] - 2, NIGERIA_BOUNDS[1] - 2],
          [NIGERIA_BOUNDS[2] + 2, NIGERIA_BOUNDS[3] + 2],
        ],
      });
      map.addControl(new mapboxgl.NavigationControl(), 'top-right');

      map.on('click', 'polling-units', async (e: any) => {
        const f = e.features?.[0];
        if (!f) return;
        const puCode = f.properties.pu_code as string;
        const statusInt = f.properties.status_int as number;
        // Fetch the full PU record from our API to populate the side panel.
        try {
          const r = await fetch(
            `/api/v1/elections/${electionId}/units?pu=${encodeURIComponent(puCode)}`
          );
          const j = await r.json();
          const unit = (j.data as PollingUnitDetail[])?.[0];
          if (unit) onSelect(unit);
          else {
            onSelect({
              pu_code: puCode,
              pu_name: puCode,
              ward_code: f.properties.ward_code,
              lga_code: f.properties.lga_code,
              state_code: f.properties.state_code,
              coordinates: { lat: e.lngLat.lat, lng: e.lngLat.lng },
              status: STATUS_INT_TO_NAME[statusInt] ?? 'no_data',
              submission_count: 0,
              source_count: 0,
              consensus_data: null,
              submissions: [],
            });
          }
        } catch {/* offline */}
      });

      map.on('mouseenter', 'polling-units', () => {
        map.getCanvas().style.cursor = 'pointer';
      });
      map.on('mouseleave', 'polling-units', () => {
        map.getCanvas().style.cursor = '';
      });

      mapRef.current = map;
    })();

    return () => {
      cancelled = true;
      if (mapRef.current) mapRef.current.remove();
      mapRef.current = null;
    };
  }, [electionId, token, onSelect]);

  return <div ref={containerRef} className="absolute inset-0" />;
}
