'use client';

import { useEffect, useRef } from 'react';
import type { PollingUnitDetail, VerificationStatus } from '@/lib/types';
import {
  buildLayers,
  buildSources,
  NIGERIA_BOUNDS,
  NIGERIA_CENTER,
} from '@/lib/mapbox-style';
import { descend, type MapFocus } from '@/lib/map-focus';

interface Props {
  electionId: string;
  token: string;
  focus: MapFocus;
  onFocus: (next: MapFocus) => void;
  onSelectPU: (unit: PollingUnitDetail) => void;
}

const STATUS_INT_TO_NAME: Record<number, VerificationStatus> = {
  0: 'no_data',
  1: 'single_source',
  2: 'inec_published',
  3: 'consensus',
  4: 'discrepancy',
  5: 'inec_confirmed',
  6: 'inec_conflict',
};

// Real Mapbox GL JS renderer. The map mounts only when a token is
// available; otherwise the parent component uses the SVG fallback. The
// vector tiles come from /api/v1/tiles, generated by PostGIS ST_AsMVT.
//
// Drill-down model (matches lib/map-focus.ts):
//   country -> click a state polygon to drill into it
//   state   -> click an LGA centroid to drill in; ward + PU layers hidden
//   lga     -> click a ward centroid to drill in; PU layer hidden
//   ward    -> PU dots become clickable; pick one to open the side pane
//
// We never show PU dots until the user has explicitly drilled into a
// single ward - even if the user manually zooms past z11.

export function MapboxRenderer({
  electionId,
  token,
  focus,
  onFocus,
  onSelectPU,
}: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<any>(null);
  // Hold the latest focus in a ref so click handlers (registered once)
  // can see the current value without us needing to re-register them.
  const focusRef = useRef(focus);
  focusRef.current = focus;
  const onFocusRef = useRef(onFocus);
  onFocusRef.current = onFocus;
  const onSelectPURef = useRef(onSelectPU);
  onSelectPURef.current = onSelectPU;

  useEffect(() => {
    if (!containerRef.current) return;
    let cancelled = false;

    (async () => {
      const mod = await import('mapbox-gl');
      // Mapbox GL CSS is imported at page level (see map/page.tsx).
      if (cancelled || !containerRef.current) return;

      const mapboxgl = (mod as any).default ?? mod;
      mapboxgl.accessToken = token;

      const tileBase =
        typeof window !== 'undefined'
          ? `${window.location.origin}/api/v1/tiles`
          : '/api/v1/tiles';

      const map = new mapboxgl.Map({
        container: containerRef.current,
        style: {
          version: 8,
          name: 'OpenBallot',
          glyphs: 'https://api.maptiler.com/fonts/{fontstack}/{range}.pbf',
          sources: {
            ...buildSources(electionId, tileBase),
            'osm-raster': {
              type: 'raster',
              tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
              tileSize: 256,
              attribution: '© OpenStreetMap contributors',
            },
          },
          layers: [
            { id: 'osm', type: 'raster', source: 'osm-raster' },
            ...(buildLayers() as any[]),
          ],
        },
        center: NIGERIA_CENTER,
        zoom: 5.5,
        minZoom: 4,
        maxZoom: 17,
        maxBounds: [
          [NIGERIA_BOUNDS[0] - 2, NIGERIA_BOUNDS[1] - 2],
          [NIGERIA_BOUNDS[2] + 2, NIGERIA_BOUNDS[3] + 2],
        ],
      });
      map.addControl(new mapboxgl.NavigationControl(), 'top-right');

      // Click handlers: registered once, dispatch based on focusRef.
      map.on('click', 'states-fill', (e: any) => {
        if (focusRef.current.level !== 'country') return;
        const f = e.features?.[0];
        if (!f) return;
        const code = (f.properties.state_code ?? f.properties.code) as string | undefined;
        const name = (f.properties.state_name ?? f.properties.name ?? code) as string | undefined;
        if (!code || !name) return;
        onFocusRef.current({ level: 'state', state_code: code, state_name: name });
      });

      map.on('click', 'lgas-circles', (e: any) => {
        if (focusRef.current.level !== 'state') return;
        const f = e.features?.[0];
        if (!f) return;
        const code = f.properties.lga_code as string | undefined;
        if (!code) return;
        const name = (f.properties.lga_name ?? code) as string;
        onFocusRef.current(descend(focusRef.current, {
          code, name, state_code: f.properties.state_code,
        }));
      });

      map.on('click', 'wards-circles', (e: any) => {
        if (focusRef.current.level !== 'lga') return;
        const f = e.features?.[0];
        if (!f) return;
        const code = f.properties.ward_code as string | undefined;
        if (!code) return;
        const name = (f.properties.ward_name ?? code) as string;
        onFocusRef.current(descend(focusRef.current, {
          code, name, state_code: f.properties.state_code,
        }));
      });

      map.on('click', 'polling-units', async (e: any) => {
        if (focusRef.current.level !== 'ward') return;
        const f = e.features?.[0];
        if (!f) return;
        const puCode = f.properties.pu_code as string;
        const statusInt = f.properties.status_int as number;
        try {
          const r = await fetch(
            `/api/v1/elections/${electionId}/units?pu=${encodeURIComponent(puCode)}`
          );
          const j = await r.json();
          const unit = (j.data as PollingUnitDetail[])?.[0];
          if (unit) onSelectPURef.current(unit);
          else {
            onSelectPURef.current({
              pu_code: puCode,
              pu_name: puCode,
              ward_code: f.properties.ward_code,
              lga_code: f.properties.lga_code,
              state_code: f.properties.state_code,
              coordinates: { lat: e.lngLat.lat, lng: e.lngLat.lng },
              status: STATUS_INT_TO_NAME[statusInt] ?? 'no_data',
              submission_count: 0,
              source_count: 0,
              consensus_data: null,
              submissions: [],
            });
          }
        } catch {/* offline */}
      });

      const setCursor = (layer: string) => {
        map.on('mouseenter', layer, () => (map.getCanvas().style.cursor = 'pointer'));
        map.on('mouseleave', layer, () => (map.getCanvas().style.cursor = ''));
      };
      setCursor('states-fill');
      setCursor('lgas-circles');
      setCursor('wards-circles');
      setCursor('polling-units');

      mapRef.current = map;
    })();

    return () => {
      cancelled = true;
      if (mapRef.current) mapRef.current.remove();
      mapRef.current = null;
    };
  }, [electionId, token]);

  // When focus changes: fit camera to the appropriate region, and
  // toggle layer visibility so only the children of the current focus
  // are interactive (and PU dots never appear outside ward focus).
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    const apply = () => {
      // Layer visibility per focus level.
      applyFocusLayers(map, focus);
      // Camera fit.
      if (focus.level === 'country') {
        map.fitBounds(NIGERIA_BOUNDS as any, { padding: 30, duration: 700 });
        return;
      }
      const bounds = computeBoundsForFocus(map, focus);
      if (bounds) {
        const maxZoom =
          focus.level === 'state' ? 9 :
          focus.level === 'lga'   ? 11 :
          15;
        map.fitBounds(bounds, { padding: 40, duration: 700, maxZoom });
      }
    };
    if (map.isStyleLoaded()) apply();
    else map.once('idle', apply);
  }, [focus]);

  return <div ref={containerRef} className="absolute inset-0" />;
}

// Show only the layers that match the current focus level, and filter
// children to those whose parent matches.
function applyFocusLayers(map: any, focus: MapFocus) {
  const show = (id: string, v: boolean) => {
    if (!map.getLayer(id)) return;
    map.setLayoutProperty(id, 'visibility', v ? 'visible' : 'none');
  };
  const setFilter = (id: string, filter: any[] | null) => {
    if (!map.getLayer(id)) return;
    map.setFilter(id, filter);
  };

  // States: always visible (the choropleth gives geographic context at
  // every level). The focused state's polygon gets a thick blue stroke
  // via the states-focus-outline layer.
  show('states-fill', true);
  show('states-circles', true);
  setFilter('states-focus-outline', [
    'all',
    ['==', ['geometry-type'], 'Polygon'],
    ['==', ['get', 'state_code'],
      focus.level === 'country' ? '__none__' : focus.state_code],
  ]);

  // LGAs visible at state focus, filtered to the focused state's LGAs.
  show('lgas-circles', focus.level === 'state');
  setFilter(
    'lgas-circles',
    focus.level === 'state' ? ['==', ['get', 'state_code'], focus.state_code] : null
  );

  // Wards visible at LGA focus, filtered to the focused LGA's wards.
  show('wards-circles', focus.level === 'lga');
  setFilter(
    'wards-circles',
    focus.level === 'lga' ? ['==', ['get', 'lga_code'], focus.lga_code] : null
  );

  // PU dots: ONLY at ward focus. Always filter to the chosen ward so
  // even a manual zoom past z11 cannot accidentally reveal 13k dots.
  show('polling-units', focus.level === 'ward');
  setFilter(
    'polling-units',
    focus.level === 'ward' ? ['==', ['get', 'ward_code'], focus.ward_code] : null
  );
}

function computeBoundsForFocus(map: any, focus: MapFocus): [[number, number], [number, number]] | null {
  if (focus.level === 'country') return null;
  if (focus.level === 'state') {
    const feats = map.querySourceFeatures('openballot', {
      sourceLayer: 'states',
      filter: ['==', ['get', 'state_code'], focus.state_code],
    });
    return computeBounds(feats);
  }
  if (focus.level === 'lga') {
    // Prefer LGA polygon if loaded; fall back to a ring of ward centroids.
    const lga = map.querySourceFeatures('openballot', {
      sourceLayer: 'lgas',
      filter: ['==', ['get', 'lga_code'], focus.lga_code],
    });
    const b = computeBounds(lga);
    if (b) return b;
    const wards = map.querySourceFeatures('openballot', {
      sourceLayer: 'wards',
      filter: ['==', ['get', 'lga_code'], focus.lga_code],
    });
    return computeBounds(wards);
  }
  // ward
  const ward = map.querySourceFeatures('openballot', {
    sourceLayer: 'wards',
    filter: ['==', ['get', 'ward_code'], focus.ward_code],
  });
  const b = computeBounds(ward);
  if (b) return b;
  const pus = map.querySourceFeatures('openballot', {
    sourceLayer: 'polling_units',
    filter: ['==', ['get', 'ward_code'], focus.ward_code],
  });
  return computeBounds(pus);
}

function computeBounds(features: any[]): [[number, number], [number, number]] | null {
  let lngMin = Infinity, lngMax = -Infinity, latMin = Infinity, latMax = -Infinity;
  let seen = false;
  const walk = (v: unknown) => {
    if (Array.isArray(v)) {
      if (typeof v[0] === 'number' && typeof v[1] === 'number') {
        const [lng, lat] = v as number[];
        if (lng < lngMin) lngMin = lng;
        if (lng > lngMax) lngMax = lng;
        if (lat < latMin) latMin = lat;
        if (lat > latMax) latMax = lat;
        seen = true;
      } else (v as unknown[]).forEach(walk);
    }
  };
  for (const f of features) walk(f?.geometry?.coordinates);
  return seen ? [[lngMin, latMin], [lngMax, latMax]] : null;
}
